version: "3"
services:
        mysql:
            image: mariadb
            ports:
                - "3260:3260"
            volumes:
                - mysql:/var/lib/mysql
            environment:
                MYSQL_ROOT_PASSWORD: DesafioTech

        wordpress:
            image: wordpress
            ports:
                - "2000:80"
            volumes:
                - DesafioTech_data:/var/www/html
            environment:
                WORDPRESS_DB_PASSWORD: DesafioTech
            depends_on:
                - mysql
            links:
                - mysql

volumes:
        mysql:
        DesafioTech_data:
